export const GEMINI_VOICE_OPTIONS = [
  { id: "Kore", label: "Kore (Female — Calm)", category: "Women" as const },
  { id: "Leda", label: "Leda (Female — Professional)", category: "Women" as const },
  { id: "Aoede", label: "Aoede (Female — Elegant)", category: "Women" as const },
  { id: "Callirrhoe", label: "Callirrhoe (Female — Soft)", category: "Women" as const },
  { id: "Autonoe", label: "Autonoe (Female — Storyteller)", category: "Women" as const },
  { id: "Fenrir", label: "Fenrir (Male — Deep)", category: "Men" as const },
  { id: "Charon", label: "Charon (Male — Mysterious)", category: "Men" as const },
  { id: "Orus", label: "Orus (Male — Confident)", category: "Men" as const },
  { id: "Alnilam", label: "Alnilam (Male — Calm)", category: "Men" as const },
  { id: "Umbriel", label: "Umbriel (Male — Authoritative)", category: "Men" as const },
  { id: "Iapetus", label: "Iapetus (Male — Energetic)", category: "Men" as const },
  { id: "Enceladus", label: "Enceladus (Male — Heavy)", category: "Men" as const },
  { id: "Puck", label: "Puck (Kids — Playful)", category: "Kids" as const },
  { id: "Zephyr", label: "Zephyr (Kids — Gentle)", category: "Kids" as const },
];

export const EDGE_VOICE_OPTIONS = [
  { id: "id-ID-GadisNeural", label: "Gadis (ID — Female Calm)", category: "Women" as const },
  { id: "id-ID-ArdiNeural", label: "Ardi (ID — Male Confident)", category: "Men" as const },
  { id: "en-US-JennyNeural", label: "Jenny (EN — Female Pro)", category: "Women" as const },
  { id: "en-US-GuyNeural", label: "Guy (EN — Male Authoritative)", category: "Men" as const },
  { id: "en-US-AriaNeural", label: "Aria (EN — Kids Cheerful)", category: "Kids" as const },
  { id: "en-US-AnaNeural", label: "Ana (EN — Kids Female)", category: "Kids" as const },
  { id: "ja-JP-NanamiNeural", label: "Nanami (JP — Female)", category: "Women" as const },
  { id: "ja-JP-KeitaNeural", label: "Keita (JP — Male)", category: "Men" as const },
];

/** Maps Gemini voice persona labels to closest Edge TTS voice for server synthesis */
export const GEMINI_TO_EDGE_VOICE: Record<string, string> = {
  Kore: "id-ID-GadisNeural",
  Leda: "en-US-JennyNeural",
  Aoede: "en-US-JennyNeural",
  Callirrhoe: "id-ID-GadisNeural",
  Autonoe: "id-ID-GadisNeural",
  Fenrir: "en-US-GuyNeural",
  Charon: "en-US-GuyNeural",
  Orus: "id-ID-ArdiNeural",
  Alnilam: "en-US-GuyNeural",
  Umbriel: "id-ID-ArdiNeural",
  Iapetus: "en-US-GuyNeural",
  Enceladus: "en-US-GuyNeural",
  Puck: "en-US-AriaNeural",
  Zephyr: "en-US-AnaNeural",
};

export const VIRAL_PRESET_OPTIONS = [
  { value: "custom", label: "✨ Custom Topic", group: "General" },
  { value: "affiliate", label: "🛍️ Product / Affiliate", group: "General" },
  { value: "kids_song", label: "🎵 Kids Song (Nursery Rhyme)", group: "Kids" },
  { value: "kids_story", label: "🦄 Kids Story & Fairy Tales", group: "Kids" },
  { value: "bedtime_story", label: "🌙 Bedtime Story", group: "Kids" },
  { value: "wayang", label: "🎭 Wayang & Folklore", group: "Kids" },
  { value: "parenting", label: "👨‍👩‍👧 Parenting Education", group: "Kids" },
  { value: "mindset", label: "🧠 Mindset & Mental", group: "Education" },
  { value: "personal_growth", label: "📈 Personal Growth", group: "Education" },
  { value: "financial_mindset", label: "💰 Financial Mindset", group: "Education" },
  { value: "social_skills", label: "🗣️ Social Skills", group: "Education" },
  { value: "motivation", label: "💪 Motivation / Life Hacks", group: "Education" },
  { value: "health", label: "💪 Health & Fitness", group: "Education" },
  { value: "fun_facts", label: "💡 Fun Facts", group: "Entertainment" },
  { value: "quiz", label: "❓ Quiz / Riddles", group: "Entertainment" },
  { value: "quotes", label: "📜 Quotes & Wisdom", group: "Entertainment" },
  { value: "bola", label: "⚽ Sports / Football", group: "Entertainment" },
  { value: "true_crime", label: "🔥 True Crime / Mystery", group: "Story" },
  { value: "horror", label: "👻 Horror / Creepy", group: "Story" },
  { value: "scifi", label: "🚀 Sci-Fi / Future", group: "Story" },
  { value: "history", label: "📜 History & War", group: "Documentary" },
  { value: "nature", label: "🌍 Nature / Disaster", group: "Documentary" },
  { value: "islami", label: "☪️ Islamic / Da'wah", group: "Faith" },
  { value: "agama_umum", label: "🕌 General Faith", group: "Faith" },
  { value: "asmr", label: "🎧 ASMR / Relaxation", group: "Relaxation" },
];

export const VIDEO_CONCEPT_OPTIONS = [
  { value: "storytelling", label: "📖 Storytelling", group: "Narrative" },
  { value: "pov", label: "👁️ POV (First Person)", group: "Narrative" },
  { value: "chronological", label: "⏳ Chronological / Timeline", group: "Narrative" },
  { value: "listicle", label: "🔢 Listicle (Top 5 / Top 10)", group: "Structured" },
  { value: "problem_solution", label: "💡 Problem & Solution", group: "Structured" },
  { value: "step_by_step", label: "🪜 Step-by-Step Tutorial", group: "Structured" },
  { value: "quick_facts", label: "⚡ Quick Facts", group: "Informative" },
  { value: "case_study", label: "🔍 Case Study", group: "Informative" },
  { value: "comparison", label: "⚖️ Comparison / Versus", group: "Informative" },
  { value: "monologue", label: "🔥 Motivational Monologue", group: "Communication" },
  { value: "qna", label: "❓ Q&A", group: "Communication" },
];

export const STRUCTURE_OPTIONS: Record<string, string[]> = {
  custom: [
    "Chronological", "Emotional Arc", "PAS Framework", "AIDA Model", "Before After",
    "Social Proof", "Plot Twist", "In Media Res", "Hero Journey", "Educational Hook",
    "Myth Buster", "Listicle", "Comparison", "Looping", "POV Relatable", "Curiosity Gap",
  ],
  true_crime: ["Chronological", "Curiosity Gap", "Plot Twist", "In Media Res", "Cold Case"],
  history: ["Chronological", "Hero Journey", "Comparison", "Myth Buster", "Cause Effect"],
  horror: ["Curiosity Gap", "In Media Res", "Plot Twist", "Slow Burn", "Jump Scare Build"],
  motivation: ["Before After", "PAS Framework", "Hero Journey", "Emotional Arc", "Stoic Lesson"],
  scifi: ["Futuristic Vision", "What If", "Techno Optimism", "Dystopian Warning", "Chronological"],
  nature: ["Cinematic Journey", "Relaxing Flow", "Educational Hook", "Comparison", "Seasonal Cycle"],
  bola: ["Match Highlight", "Player Profile", "Match Analysis", "History Moment", "Rivalry Story"],
  islami: ["Quranic Reflection", "Hadith Story", "Islamic History", "Daily Dua", "Moral Lesson"],
  mindset: ["Stoic Lesson", "Mindshift Moment", "Daily Habit", "Before After", "POV Relatable"],
  health: ["Daily Routine", "Myth Buster", "Quick Tip", "Transformation", "Science Fact"],
  affiliate: [
    "AIDA (Hard Sell)", "PAS (Problem-Solution)", "Unboxing & Review",
    "Comparison (Vs Competitor)", "Social Proof / Testimonial", "Soft Selling Story",
  ],
  kids_story: ["Once Upon a Time", "Character Goal", "Fun Obstacle", "Happy Solution", "Moral Lesson"],
  social_skills: ["Charisma Hack", "Conversation Opener", "Body Language", "Mistake Fix", "Psychology Trick"],
  personal_growth: ["Habit Stacking", "Productivity Hack", "Morning Routine", "Book Summary", "Life Lesson"],
  financial_mindset: ["Money Trap", "Saving Hack", "Investment 101", "Rich vs Poor", "Compound Effect"],
  kids_song: ["Verse Chorus", "Counting Song", "Story Song", "Daily Routine", "Repetitive Learning", "Alphabet Style"],
  wayang: ["Dalang Opening", "Conflict Introduction", "Battle/Gara-Gara", "Wisdom Resolution", "Moral Closing"],
  bedtime_story: ["Gentle Intro", "Comfortable Setting", "Slow Journey", "Resolution of Peace", "Sleepy Closing"],
  parenting: ["Relatable Struggle", "Empathy Connection", "Practical Tip", "Scientific Backing", "Encouragement"],
  agama_umum: ["Spiritual Hook", "Historical Context", "Moral Lesson", "Daily Application", "Peaceful Outro"],
  fun_facts: ["Strong Hook", "Fact 1", "Fact 2", "Mindblowing Fact", "CTA Question"],
  quotes: ["Visual Aesthetic", "Opening Quote", "Deep Meaning", "Reflection", "Soothing Outro"],
  quiz: ["Challenge Hook", "Question", "Think Time (Timer)", "Answer", "Score & CTA"],
  asmr: ["Suara Pemicu", "Visual Satisfying", "Transisi Halus", "Klimaks ASMR", "Fade Out"],
  default: ["Chronological", "Emotional Arc", "Hook-Body-CTA", "Problem-Solution"],
};

/** Narration tone personas — injected into script prompt (Gemini Canvas) */
export const TONE_PROMPTS: Record<string, string> = {
  ghost_whisperer: "Whispering, airy, eerie, close proximity to mic, mysterious. Tempo: Slow with long pauses.",
  deep_ominous: "Deep male voice, slow tempo, serious, ominous, intimidating, breathy.",
  cold_detective: "Flat tone, analytical, serious, detached, true crime narrator style.",
  epic_narrator: "Cinematic, movie trailer voice, epic, deep, grandiose.",
  historian: "Authoritative, knowledgeable, formal, documentary style, clear articulation.",
  somber_reporter: "Sad, empathetic, respectful, slow pace, emotional.",
  innovator: "Crisp, intelligent, fast-paced, enthusiastic, tech-savvy.",
  futurist: "Inspirational, awe-inspiring, hopeful, smooth, warm.",
  cybernetic: "Precise, neutral, clean, modern, slight digital feel.",
  action_hero: "Urgent, intense, gritty, adrenaline, fast-paced.",
  survivalist: "Raspy, gravelly voice, tough, masculine, adventurous.",
  awe_struck: "Amazed, wondering, soft, breathy, admiring.",
  friendly_pal: "Casual, conversational, friendly, smiling voice, engaging.",
  curious_geek: "Curious, inquisitive, bright, energetic, youthful.",
  witty: "Witty, slightly sarcastic, entertaining, fun.",
  cheerful_singer: "High pitch, enthusiastic, singing tone, slow tempo, very clear articulation, nursery rhyme style.",
  storyteller_mom: "Warm, motherly, soft, soothing, clear and slow for children.",
};

export const TONE_OPTIONS = [
  { value: "friendly_pal", label: "Friendly Pal (Casual)" },
  { value: "epic_narrator", label: "Epic Narrator (Cinematic)" },
  { value: "cold_detective", label: "Cold Detective (True Crime)" },
  { value: "ghost_whisperer", label: "Ghost Whisperer (Horror)" },
  { value: "cheerful_singer", label: "Cheerful Singer (Kids)" },
  { value: "storyteller_mom", label: "Storyteller Mom (Bedtime)" },
  { value: "action_hero", label: "Action Hero (Energetic)" },
  { value: "historian", label: "Historian (Documentary)" },
  { value: "witty", label: "Witty (Entertaining)" },
  { value: "curious_geek", label: "Curious Geek (Facts)" },
];

export const COLOR_MOOD_OPTIONS = [
  "Natural",
  "Warm/Sepia",
  "Cool/Night",
  "Dark/Moody",
  "Vibrant/Pop",
  "Cinematic Teal-Orange",
  "Pastel Dream",
  "High Contrast B&W",
];

export const VISUAL_STYLE_OPTIONS = [
  "3D Cute Animation (Pixar Style)",
  "Photorealistic",
  "Claymation (Stop Motion)",
  "Cartoon Vector",
  "Cinematic 4K",
  "Anime Style",
  "Watercolor / Pastel",
  "Wayang Kulit Art",
  "Cyberpunk Cityscape",
  "Studio Ghibli Animation",
  "Dark Fantasy / Gothic",
  "Ukiyo-e (Traditional Japanese)",
  "Retro Comic Book",
  "Synthwave / Vaporwave",
  "Oil Painting Masterpiece",
  "Steampunk",
  "Origami Paper Art",
  "Low Poly 3D",
  "Neon Noir",
  "Pencil Sketch",
  "Surrealism",
  "Knitted/Crochet 3D",
  "3D Render / CGI",
  "Cinematic Cyberpunk 2077",
  "Dark Academia",
  "Retro 80s Anime",
  "Unreal Engine 5 Render",
  "Midjourney V6 Masterpiece",
  "Isometric 3D",
  "Pop Art",
  "GTA V Loading Screen",
  "Cybernetic HDR",
  "Dreamy Fantasy",
];

export const LANGUAGE_OPTIONS = [
  "English",
  "Japanese",
  "Korean",
  "Chinese",
  "Arabic",
  "Hindi",
  "Spanish",
  "French",
  "German",
  "Russian",
  "Portuguese",
  "Italian",
];

export const PLATFORM_OPTIONS = [
  { value: "youtube_shorts", label: "Shorts / TikTok (9:16)", aspectRatio: "9:16" as const },
  { value: "youtube_long", label: "YouTube Long (16:9)", aspectRatio: "16:9" as const },
  { value: "instagram", label: "Instagram Reels (9:16)", aspectRatio: "9:16" as const },
];

export const DEFAULT_CTA =
  "Don't forget to Like & Subscribe for more!";

export const DEFAULT_CREATE_FORM = {
  useBuiltInGemini: true,
  apiEngine: "gemini",
  viralPreset: "custom",
  productName: "",
  productBenefits: "",
  productImage: null as string | null,
  videoConcept: "storytelling",
  topic: "",
  topicContext: "",
  narrativeStructure: "Chronological",
  scriptStyle: "narration" as const,
  duration: "60",
  platform: "youtube_shorts",
  aspectRatio: "9:16" as const,
  numScenes: 5,
  style: "Photorealistic",
  language: "English",
  tone: "friendly_pal",
  colorMood: "Natural",
  audioEngine: "gemini" as const,
  narrator: "Kore",
  voiceSpeed: 1.0,
  includeCTA: true,
  useThumbnail: false,
  ctaText: DEFAULT_CTA,
  charImage: null as string | null,
};

export function structureOptionsFor(preset: string): string[] {
  return STRUCTURE_OPTIONS[preset] ?? STRUCTURE_OPTIONS.custom;
}
